# Generated by Django 3.2.22 on 2023-11-04 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231103_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6dda13b7-e324-4519-ab29-f840b78bdd90'), primary_key=True, serialize=False, unique=True),
        ),
    ]
