# Generated by Django 4.2.6 on 2023-11-05 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("357bc064-fbdd-4980-a210-079be62e9439"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
