# Generated by Django 4.2.6 on 2023-11-06 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("da125c4e-e24f-430a-83d0-c5ea320fb368"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
