# Generated by Django 4.2.6 on 2023-11-06 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4de44e53-2bd2-4050-b565-f8c262cc88f0"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
