# Generated by Django 4.2.6 on 2023-12-01 22:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1be0be20-d646-42f7-80cf-a82de89fed66"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
