# Generated by Django 4.2.6 on 2023-12-01 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("93da3389-a5e5-4891-9024-ff93ca406496"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
