# Generated by Django 4.2.6 on 2023-12-01 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="subjecct",
            new_name="subject",
        ),
    ]
